version: "3.1"
services:
  nginx:
    build: "./nginx/" # 使用 nginx 下的 Dockerfile
    # image: nginx:1.15.1-alpine
    container_name: lamp_nginx
    ports: # 外部機器:內部機器
      - "7777:80"
    expose:
      - "80"
    links:
      - php
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/conf.d

  php:
    build: "./php/" # 使用php directory 下的 Dockerfile
    # image: php:7.0-fpm
    container_name: lamp_php
    expose: # container 之間的連接接口
      - "9000"
    links:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:latest
    container_name: lamp_mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    volumes:
      - /var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    ports:
      - "9001:80"
    expose:
      - "80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql